data:
  data_file: /workspaces/deburring_diffusion/results/traj_generator/multiple_configuration_multiple_poses.json
trainer:
  max_epochs: 1000
  default_root_dir: /workspaces/deburring_diffusion/results/diffusion